package ch.supsi.dti.parser;

import ch.supsi.dti.multilanguage.Messages;
/* Generated By:JavaCC: Do not edit this line. CommandParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommandParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INFO = 5;
  /** RegularExpression Id. */
  int OPEN = 6;
  /** RegularExpression Id. */
  int EXPAND = 7;
  /** RegularExpression Id. */
  int SELECT = 8;
  /** RegularExpression Id. */
  int BINARY = 9;
  /** RegularExpression Id. */
  int PROJECT = 10;
  /** RegularExpression Id. */
  int PACKAGE = 11;
  /** RegularExpression Id. */
  int METHOD = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int SINGLES = 14;
  /** RegularExpression Id. */
  int PROJECTS = 15;
  /** RegularExpression Id. */
  int PACKAGES = 16;
  /** RegularExpression Id. */
  int CLASSES = 17;
  /** RegularExpression Id. */
  int METHODS = 18;
  /** RegularExpression Id. */
  int EDITOR = 19;
  /** RegularExpression Id. */
  int CURSOR = 20;
  /** RegularExpression Id. */
  int DEFAULTS = 21;
  /** RegularExpression Id. */
  int DEFAULTT = 22;
  /** RegularExpression Id. */
  int SELECTED = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int INTEGER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int LINE_COMMENT = 28;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 29;
  /** RegularExpression Id. */
  int IDENTIFIER = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 32;
  /** RegularExpression Id. */
  int BIND = 33;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 34;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    Messages.CommandParserConstants_0,
    Messages.CommandParserConstants_1,
    Messages.CommandParserConstants_2,
    Messages.CommandParserConstants_3,
    Messages.CommandParserConstants_4,
    Messages.CommandParserConstants_5,
    Messages.CommandParserConstants_6,
    Messages.CommandParserConstants_7,
    Messages.CommandParserConstants_8,
    Messages.CommandParserConstants_9,
    Messages.CommandParserConstants_10,
    Messages.CommandParserConstants_11,
    Messages.CommandParserConstants_12,
    Messages.CommandParserConstants_13,
    Messages.CommandParserConstants_14,
    Messages.CommandParserConstants_15,
    Messages.CommandParserConstants_16,
    Messages.CommandParserConstants_17,
    Messages.CommandParserConstants_18,
    Messages.CommandParserConstants_19,
    Messages.CommandParserConstants_20,
    Messages.CommandParserConstants_21,
    Messages.CommandParserConstants_22,
    Messages.CommandParserConstants_23,
    Messages.CommandParserConstants_24,
    Messages.CommandParserConstants_25,
    Messages.CommandParserConstants_26,
    Messages.CommandParserConstants_27,
    Messages.CommandParserConstants_28,
    Messages.CommandParserConstants_29,
    Messages.CommandParserConstants_30,
    Messages.CommandParserConstants_31,
    Messages.CommandParserConstants_32,
    Messages.CommandParserConstants_33,
    Messages.CommandParserConstants_34,
    Messages.CommandParserConstants_35,
  };

}
