package ch.supsi.dti.parser;
/* Generated By:JavaCC: Do not edit this line. CommandParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommandParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GETINFO = 5;
  /** RegularExpression Id. */
  int OPEN = 6;
  /** RegularExpression Id. */
  int SET = 7;
  /** RegularExpression Id. */
  int BINARY = 8;
  /** RegularExpression Id. */
  int METHOD = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int SINGLES = 11;
  /** RegularExpression Id. */
  int EDITOR = 12;
  /** RegularExpression Id. */
  int CURSOR = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int FLOAT = 15;
  /** RegularExpression Id. */
  int INTEGER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int LINE_COMMENT = 18;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 22;
  /** RegularExpression Id. */
  int BIND = 23;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 24;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"GETINFO\"",
    "\"OPEN\"",
    "\"SET\"",
    "<BINARY>",
    "\"METHOD\"",
    "\"CLASS\"",
    "<SINGLES>",
    "\"EDITOR\"",
    "\"CURSOR\"",
    "<NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<BIND>",
    "<CHAR_LITERAL>",
    "<QUOTED_IDENTIFIER>",
  };

}
